
<center>
<br><br>
<button class="btn btn-success" onclick="location.href='/admin/usuarios/index'">Gerenciar Usuários</button>
<br><br>
<button class="btn btn-success" onclick="location.href='/admin/posts/index'">Gerenciar Posts</button>
<br><br>
<button class="btn btn-success" onclick="location.href='/admin/comentarios/index'">Gerenciar Comentários</button>
<br><br>
<button class="btn btn-success" onclick="location.href='/admin/relacionamentos/index'">Gerenciar Relacionamentos</button>
<br><br>
<button class="btn btn-success" onclick="location.href='/admin/eventos/index'">Gerenciar Eventos</button>
</center>