<div class="container">
    <div class="col-md-12 col-md-offset-4">
        <div class="col-md-4">

          <form class="form-signin" method="POST" action="/admin/login/login">
            <h2 class="form-signin-heading">Faça login</h2>
            <label for="inputEmail" class="sr-only">Endereço de e-mail</label>
            <input type="email" name="email" id="email" class="form-control" placeholder="Endereço de e-mail" required autofocus>
            <label for="inputPassword" class="sr-only">Senha</label>
            <input type="password" name="senha" id="senha" class="form-control" placeholder="Senha" required>
            <div class="checkbox">
              <label>
              </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
          </form>
        </div>
    </div>
</div> <!-- /container -->