<?php

  if ($resultado == FALSE){
    echo "<div class='alert alert-warning' align='center'><h1>Desculpe não encontramos que você procura :(</h1></div>";
    echo "<meta HTTP-EQUIV='refresh' CONTENT='3;URL=/'>";
  }
  
?>


<div class="container">
  <div class="row">
    
    <div class="col-md-12"> 
      
      <div class="panel">
        <div class="panel-body">     

     <?php foreach($usuarios as $usuario) { ?>
      <div class="row">    
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="/admin/perfil/get-photo/id/<?php echo $usuario->getId(); ?>" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <h3><?php echo $usuario->getNome()." ".$usuario->getSobrenome(); ?></h3>
              <div class="row">
                <div class="col-xs-9">
                  <p class="lead"><a class="btn btn-default" href="/admin/exibirperfil/index/id/<?php echo $usuario->getId(); ?>">Ver perfil</a></p>
                </div>
              </div>
            <div class="col-xs-3"></div>
          </div>
        <br><br>
      </div>
    <hr>

    <?php } ?>
    <?php foreach($eventos as $evento) { ?>
      <div class="row">    
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="/img/postdefault.jpg" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <h3><?php echo $evento->getTitulo(); ?></h3>
              <div class="row">
                <div class="col-xs-9">
                  <p><?php echo $evento->getMintext(); ?></p>
                  <p class="lead"><a class="btn btn-default" href="/admin/exibirevento/index/id/<?php echo $evento->getId(); ?>">Visualizar</a></p>
                  <p class="pull-right"><span class="label label-default">keyword</span> <span class="label label-default">tag</span> <span class="label label-default">evento</span></p>
                  <ul class="list-inline"><li><i>Ultima Edição:</i> <?php echo $evento->getDataEvento(); ?></li><li><a href="/admin/exibirevento/index/id/<?php echo $evento->getId(); ?>"><i class="glyphicon glyphicon-comment"></i> <?php echo count($evento->getComentarios()); ?> Comentários</li>
                    <li>Participantes: <?php echo count($evento->getParticipantes()); ?></li></a>
                  </ul>
                  </div>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          <hr>

    <?php } ?>        
          
        </div>
      </div>
                                      
    </div><!--/col-12-->
  </div>
</div>
</hr>
<?php

echo $this->paginationControl(
    // o objeto de paginacao
    $paginas,
    //tipos de paginacao (elastic, all, sliding, Juping) mais em zend/paginator exemple-pagination-controls
    'sliding',
    // a parcial usada para gerar o html para a paginacao
    'admin/partials/paginator/paginator.phtml',
    //a rota utulizada na paginacao
    array(
        'route' => 'pesquisas'
    )
);
?>