<div class="container">
  <div class="row">
    
    <div class="col-md-12"> 
      
      <div class="panel">
        <div class="panel-body">     

     <?php foreach($posts as $post) {
      $jamostrou="nao";
       foreach($meusdados as $userlogado) {
                foreach($userlogado->getAmigos() as $amigo) {
                    if($amigo->getId() == $post->getDono()->getId()){
        if($post->getVisibilidade()=="somente amigos" OR $post->getVisibilidade()=="publico" ){
      ?>
      <div class="row">  
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="/img/postdefault.jpg" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <?php if($post->getPhoto()){ ?>
                <a class="story-img" href="#"><img src="/admin/posts/get-photo/id/<?php echo $post->getId(); ?>" style="width:300px;height:260px" class="img-thumbnail"></a>
              <?php } ?>
              <h3><?php echo $post->getTitulo(); ?></h3>
              <div class="row">
                <div class="col-xs-9">
                  <p><?php echo $post->getPostComp(); ?></p>
                  <ul class="list-inline"><li><i>Ultima Edição:</i> <?php echo $post->getDataPost(); ?></li><li><a href="/admin/exibirpost/index/id/<?php echo $post->getId(); ?>"><i class="glyphicon glyphicon-comment"></i> <?php echo count($post->getComentarios()); ?> <i class="glyphicon glyphicon-thumbs-up"></i> <?php echo count($post->getCurtiram()); ?> <i class="glyphicon glyphicon-thumbs-down"></i> <?php echo count($post->getNaocurtiram()); ?> </a></li></ul>
                  <ul>Postado por: <a href="/admin/exibirperfil/index/id/<?php echo $post->getDono()->getId(); ?>"><?php echo $post->getDono()->getNome() ?></a></ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>

    <?php 
           $jamostrou="sim";
           }//fim do if visibilidade 
          }//fim do if verificar se é amigos
        }//fim fo if userlogado->getAmigos
      }//fim do if visibilidade


       if($post->getVisibilidade()=="publico" && $jamostrou=="nao" && $post->getDono()->getId()!=$this->session()->offsetGet('user')->getId() ){
      ?>
      <div class="row">    
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="/img/postdefault.jpg" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <?php if($post->getPhoto()){ ?>
                <a class="story-img" href="#"><img src="/admin/posts/get-photo/id/<?php echo $post->getId(); ?>" style="width:300px;height:260px" class="img-thumbnail"></a>
              <?php } ?>
              <h3><?php echo $post->getTitulo(); ?></h3>
              <div class="row">
                <div class="col-xs-9">
                  <p><?php echo $post->getPostComp(); ?></p>
                  <ul class="list-inline"><li><i>Ultima Edição:</i> <?php echo $post->getDataPost(); ?></li><li><a href="/admin/exibirpost/index/id/<?php echo $post->getId(); ?>"><i class="glyphicon glyphicon-comment"></i> <?php echo count($post->getComentarios()); ?> <i class="glyphicon glyphicon-thumbs-up"></i> <?php echo count($post->getCurtiram()); ?> <i class="glyphicon glyphicon-thumbs-down"></i> <?php echo count($post->getNaocurtiram()); ?> </a></li></ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>

    <?php 
           }//fim do if visibilidade publico
    }//fim do foreach posts 
    ?>       
          
        </div>
      </div>
                                      
    </div><!--/col-12-->
  </div>
</div>
</hr>
<br><br>

<?php 

$flag="nada";// padrao, se nao for pessoa logada ou se nao tiver curtido/nao curtido

if($post->getDono()->getId()==$this->session()->offsetGet('user')->getId()){
    ?>
      <div class="row">    
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="/img/postdefault.jpg" style="width:100px;height:100px" class="img-circle"></a> 
            </div>
            <div class="col-md-10 col-sm-9">
              <?php if($post->getPhoto()){ ?>
                <a class="story-img" href="#"><img src="/admin/posts/get-photo/id/<?php echo $post->getId(); ?>" style="width:300px;height:260px" class="img-thumbnail"></a>
              <?php } ?>
              <h3><?php echo $post->getTitulo(); ?></h3>
              <div class="row">
                <div class="col-xs-9">
                  <p><?php echo $post->getPostComp(); ?></p>
                  <ul class="list-inline"><li><i>Ultima Edição:</i> <?php echo $post->getDataPost(); ?></li><li><a href="/admin/exibirpost/index/id/<?php echo $post->getId(); ?>"><i class="glyphicon glyphicon-comment"></i> <?php echo count($post->getComentarios()); ?> <i class="glyphicon glyphicon-thumbs-up"></i> <?php echo count($post->getCurtiram()); ?> <i class="glyphicon glyphicon-thumbs-down"></i> <?php echo count($post->getNaocurtiram()); ?> </a></li></ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>
    <?php
  $flag="postDoUserLogado";
}// fim do if verifica se é meu post

//começo verifica se ja curtiu ou se ja nao curtiu o post
  foreach($post->getCurtiram() as $curtiu) { 
        if($curtiu->getId()==$this->session()->offsetGet('user')->getId()){
          $flag="jaCurtiu";
        }
  } 
 
  foreach($post->getNaocurtiram() as $naoCurtiu) {
        if($naoCurtiu->getId()==$this->session()->offsetGet('user')->getId()){
          $flag="jaNaoCurtiu";
        } 
  } 
//fim verifica se ja curtiu ou se ja nao curtiu o post  

if($flag=="postDoUserLogado"){ ?>
  <div class="col-md-12"> 
    <div class="well">
        <h4>Esse é seu post</h4>                 
    </div>
</div>
<?php
} /*fim do if flag postDoUserLogado*/ 

if($post->getVisibilidade()=="somente eu"){ ?>
  <div class="col-md-12"> 
    <div class="well">
        <h4>Somente o dono do Post pode ve-lo</h4>                 
    </div>
</div>
<?php
} /*fim do if flag postDoUserLogado*/

if($flag=="nada"){
?>
<!-- likes -->
    <div class="col-md-12"> 
    <div class="well">
        <h4>Curta ou nao o post</h4>
        <form method="POST" action="/admin/posts/curtidas/" role="form" class="clearfix"> 
          <input type="hidden" name="opcao" value="curtir"  id="opcao">          
          <input type="hidden" name="id_post" value=<?php echo $post->getId(); ?>  id="id_post">
          <button type="submit" class="btn btn-primary">Curtir</button>
        </form>  
        <form method="POST" action="/admin/posts/curtidas" role="form" class="clearfix"> 
          <input type="hidden" name="opcao" value="naocurtir"  id="opcao">          
          <input type="hidden" name="id_post" value=<?php echo $post->getId(); ?>  id="id_post">
          <button type="submit" class="btn btn-primary">Nao Curtir</button>
        </form>                  
    </div>
</div>
<?php }/*fim do if flag nada*/  

if($flag=="jaCurtiu"){
?>
<!-- likes -->
    <div class="col-md-12"> 
    <div class="well">
         <h5>Atenção!, vc ja curtiu esse post</h5>
        <h4>remover curtida?</h4>
        <form method="POST" action="/admin/posts/curtidas" role="form" class="clearfix">
            <div class="col-md-6 form-group">
            <input type="hidden" name="opcao" value="removercurtida"  id="opcao">
                <input type="hidden" name="id_post" value=<?php echo $post->getId(); ?>  id="id_post">
                <button type="submit" class="btn btn-primary">Sim</button>
            </div>
        </form>                  
    </div>
</div>
<?php }/*fim do if flag jaCurtiu*/ 

if($flag=="jaNaoCurtiu"){
?>
<!-- likes -->
    <div class="col-md-12"> 
    <div class="well">
        <h5>Atenção!, vc ja nao curtiu esse post</h5>
        <h4>remover nao curtida?</h4>
        <form method="POST" action="/admin/posts/curtidas" role="form" class="clearfix">
            <div class="col-md-6 form-group">
            <input type="hidden" name="opcao" value="removernaocurtida"  id="opcao">
                <input type="hidden" name="id_post" value=<?php echo $post->getId(); ?>  id="id_post">
                <button type="submit" class="btn btn-primary">Sim</button>
            </div>
        </form>                 
    </div>
</div>
<?php }/*fim do if flag jaNaoCurtiu*/ ?> 

<!-- likes -->
<div class="row">
<div class="col-md-10 col-sm-9">
<?php 
if(count($post->getCurtiram())>0){
    ?>
   <h4>Quem Curtiu(<?php echo count($post->getCurtiram()); ?>):</h4>
    <?php
foreach($post->getCurtiram() as $curtiu) { ?>
   <h5> <a href="/admin/exibirperfil/index/id/<?php echo $curtiu->getId(); ?>"><?php echo $curtiu->getNome()?></a></h5>
<?php 
  }//fim do foreach
}//fim do if
 ?>
</div>
</div>

<!-- likes -->
<div class="row">
<div class="col-md-10 col-sm-9">
<?php 
if(count($post->getNaoCurtiram())>0){
    ?>
    <h4>Quem Nao-Curtiu(<?php echo count($post->getNaoCurtiram()); ?>):</h4>
    <?php
 foreach($post->getNaocurtiram() as $naoCurtiu) { ?>
     <h5> <a href="/admin/exibirperfil/index/id/<?php echo $naoCurtiu->getId(); ?>"><?php echo $naoCurtiu->getNome()?></a></h5>
<?php 
 }//fim do foreach
}//fim do if
?>
</div>
</div>

<!-- Posted Comments -->
<!-- Comment -->
<?php foreach($post->getComentarios() as $comentario) { ?>
<div class="media">
    <a class="pull-left" href="/admin/exibirperfil/index/id/<?php echo $comentario->getUsuario()->getId(); ?>">
        <img class="media-object" style="width:64px;height:64px" src="/img/profile.jpg" alt="">
    </a>
    <div class="media-body">
        <h4 class="media-heading"><?php echo $comentario->getUsuario()->getNome(); ?>
            <small><?php echo $comentario->getDataComentario(); ?></small>
        </h4>
        <?php  echo $comentario->getComentario(); ?>
    </div>
</div>
<?php } ?>

<br><br>
<!-- Blog Comments -->
<!-- Comments Form -->
    <div class="col-md-12"> 
        <div class="col-md-12">
    <div class="well">
     
        <h4>Deixe seu comentário</h4>
     
        <form method="POST" action="/admin/comentarios/novo/" role="form" class="clearfix">
     
            <div class="col-md-12 form-group">
                <label class="sr-only" for="email">Comentário</label>
                <textarea class="form-control" name="comentario" id="comentario" placeholder="Comentário"></textarea>
            </div>
     
            <div class="col-md-12 form-group text-right">
                <input type="hidden" name="id_post" value=<?php echo $post->getId(); ?>  id="id_post">
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
     
        </form>                   
    </div>
</div>
</div>