<button class="btn btn-success" onclick="location.href='/admin/comentarios/save'">Novo Comentario</button>

<table class="table">
    <thead>
    <tr>
       <b> <td>Id</td><td>Email</td><td>Comentario</td><td>Data Comentario</td><td>Editar</td><td>Excluir</td></tr></b>
    </tr>
    </thead>
    <tbody>
    <?php foreach($comentarios as $comentario) {
        ?>
        <tr>
            <td>
                <?php echo $comentario->getId(); ?>
            </td>
            <td>
                <?php echo $comentario->getEmail(); ?>
            </td>
            <td>
                <?php echo $comentario->getComentario(); ?>
            </td>
            <td>
                <?php echo $comentario->getDataComentario(); ?>
            </td>
            <td>
                <a class="btn btn-success" href="/admin/comentarios/save/id/<?php echo $comentario->getId(); ?>">Editar</a>
            </td>
            <td>
                <a class="btn btn-danger" href="/admin/comentarios/delete/id/<?php echo $comentario->getId(); ?>">Excluir</a>
            </td>
        </tr>
    <?php 
		}
    ?>
    </tbody>

</table>

<?php

echo $this->paginationControl(
    // o objeto de paginacao
    $comentarios,
    //tipos de paginacao (elastic, all, sliding, Juping) mais em zend/paginator exemple-pagination-controls
    'sliding',
    // a parcial usada para gerar o html para a paginacao
    'admin/partials/paginator/paginator.phtml',
    //a rota utulizada na paginacao
    array(
        'route' => 'comentarios'
    )
);
?>