<div class="container">
  <div class="row">
    
    <div class="col-md-12"> 
      <?php 
        $id_logado = $this->session()->offsetGet('user')->getId();
        if ($id_logado == (int)$id_album){ 
        ?>
        <button class="btn btn-success" onclick="location.href='/admin/album/save'">Novo foto</button>
        <?php
        }
      ?>
      
      <div class="panel">
        <div class="panel-body">     

     <?php foreach($fotos as $foto) { ?>
      <div class="row">    
            <br>
            <div class="col-md-2 col-sm-12 text-center">
              <img class="img-thumbnail" alt="<?php echo $foto->getTitulo();?>" src="/admin/album/get-photo/id/<?php echo $foto->getId(); ?>"/>
            </div>
            <div class="col-md-6 col-sm-2">
              <h3><?php echo $foto->getTitulo(); ?></h3>
              <div class="row">
                <div class="col-xs-4">
                  <ul class="list-inline"><li><i>Upload: </i><?php echo $foto->getDataAlbum(); ?>
                  </div>
                  <?php if ($id_logado == (int)$id_album){  ?>
                    <button class="btn btn-danger" onclick="location.href='/admin/album/delete/id/<?php echo $foto->getId(); ?>'">Deletar</button>
                  <?php } ?>
                  </div>
              </div>
            </div>
            <?php }?>
           <hr>
          </div>
      </div>                              
    </div><!--/col-12-->
  </div>
</div>
</hr>

