<div class="container">
  <div class="row">
    
    <div class="col-md-12"> 
      
      <div class="panel">
        <div class="panel-body">     

     <?php foreach($usuarios as $usuario) { ?>
      <div class="row">    
            <br>
            <div class="col-md-10 col-sm-9">
              <h3>Nome: <?php echo $usuario->getNome(); ?></h3>
              <br><br>
              <h3>Sobrenome: <?php echo $usuario->getSobrenome(); ?></h3>
            </div>
          </div>
          
          
          
        </div>
      </div>

      
      <div class="row">    
            <br>
            <div class="col-md-10 col-sm-9">
              <h2>Amigos:</h2>
              <?php
              foreach($usuario->getAmigos() as $amigo) {
                   ?>
                   <h4><br>Amigo: <a href="/admin/exibirperfil/index/id/<?php echo $amigo->getId() ?>">Ver Perfil</a></h4>
                   <?php
                }
               ?> 
              
            </div>
          </div>
          <hr>
    <?php }//fim foreach usuarios
     ?>
                                      
    </div><!--/col-12-->
  </div>
</div>
</hr>
<br><br>




<?php       

        $flag="naoeamigo";

      foreach($meusdados as $userlogado) { 
           foreach($userlogado->getSolicitacoes() as $jasolicitou) {
                      if($jasolicitou->getId() == $usuario->getId()){
                      $flag="usuariojasolicitou";
                      }
                }  
         }


        if($usuario->getId()==$this->session()->offsetGet('user')->getId()){
          $flag="evc";
        }

        foreach($usuario->getSolicitacoes() as $solicitou) {
                    if($solicitou->getId() == $this->session()->offsetGet('user')->getId()){
                      $flag="jasolicitou";
                    }
                }

              

          foreach($usuario->getAmigos() as $amigo) {
                    if($amigo->getId() == $this->session()->offsetGet('user')->getId()){
                      $flag="eamigo";
                    }
                }


          if($flag=="naoeamigo"){     
              ?>

        <h4>Solicitar amizade?</h4>
        <form method="POST" action="/admin/usuarios/solicitaramizade" role="form" class="clearfix">
            <div class="col-md-6 form-group">
            <input type="hidden" name="opcao" value="solicitar"  id="opcao">
                <input type="hidden" name="id_usuario" value=<?php echo $usuario->getId(); ?>  id="id_usuario">
                <button type="submit" class="btn btn-primary">Sim</button>
            </div>
        </form>  

        <?php     

          }

          if($flag=="eamigo"){
          ?>
            <h5>Atenção!, vc ja é amigo dessa pessoa.</h5>
           <h4>Remover amizade?</h4>
        <form method="POST" action="/admin/usuarios/solicitaramizade" role="form" class="clearfix">
            <div class="col-md-6 form-group">
            <input type="hidden" name="opcao" value="remover"  id="opcao">
                <input type="hidden" name="id_usuario" value=<?php echo $usuario->getId(); ?>  id="id_usuario">
                <button type="submit" class="btn btn-primary">Sim</button>
            </div>
        </form> 

          <?php
        }

        if($flag=="jasolicitou"){
           echo"<h4>Vc ja solicitou amizade com essa pessoa</h4>"; 
        }
        

        if($flag=="evc"){
           echo"<h4>Esse é seu perfil</h4>"; 
           ?>
           <a class="btn btn-success" href="/admin/perfil/save/id/<?php echo $usuario->getId(); ?>">Editar perfil</a>
           <?php
        }


        if($flag=="usuariojasolicitou"){     
              ?>
        <h5>Atenção!, essa pessoa ja solicitou sua amizade.</h5>
        <h4>aceitar amizade?</h4>
        <form method="POST" action="/admin/usuarios/solicitaramizade" role="form" class="clearfix">
            <div class="col-md-6 form-group">
            <input type="hidden" name="opcao" value="aceitar"  id="opcao">
                <input type="hidden" name="id_usuario" value=<?php echo $usuario->getId(); ?>  id="id_usuario">
                <button type="submit" class="btn btn-primary">Sim</button>
            </div>
        </form>
        <form method="POST" action="/admin/usuarios/solicitaramizade" role="form" class="clearfix">
                    <input type="hidden" name="opcao" value="negar"  id="opcao">
                     <input type="hidden" name="id_usuario" value=<?php echo $usuario->getId(); ?>  id="id_usuario">
                    <button type="submit" class="btn btn-primary">Não</button>
        </form>   

        <?php     

          }
            ?>