<?php
foreach($usuarios as $usuario) { 

      $jamostrou="nao";
       $flag="naoeamigo";

      foreach($usuario->getAmigos() as $amigo) {
                    if($amigo->getId() == $this->session()->offsetGet('user')->getId()){
                      $flag="eamigo";
                    }
                }

      if($usuario->getId()==$this->session()->offsetGet('user')->getId()){
          $flag="evc";
        }

        foreach($meusdados as $userlogado) { 
           foreach($userlogado->getSolicitacoes() as $jasolicitou) {
                      if($jasolicitou->getId() == $usuario->getId()){
                      $flag="usuariojasolicitou";
                      }
                }  
         }

        foreach($usuario->getSolicitacoes() as $solicitou) {
                    if($solicitou->getId() == $this->session()->offsetGet('user')->getId()){
                      $flag="jasolicitou";
                    }
                }
        ?>
         
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="row clearfix">
				<div class="col-md-2 column">
					<div class="fotoPerfil">	
            <img src="/admin/perfil/get-photo/id/<?php echo $usuario->getId(); ?>" style="width:160px;height:160px" class="img-thumbnail">
					</div>
					<div class="panel panel-default">
						<?php if($flag=="evc"){?>
						<div class="panel-footer">						 
				           <a class="btn btn-success" href="/admin/perfil/save/id/<?php echo $usuario->getId(); ?>">Editar perfil</a>
						</div>
						<?php } ?>
						<div class="panel-footer">
						<?php if($flag=="eamigo"){ ?>
		        				<form method="POST" action="/admin/usuarios/solicitaramizade" role="form" class="clearfix">
		            			<div class="col-md-6 form-group">
		            			<input type="hidden" name="opcao" value="remover"  id="opcao">
		                		<input type="hidden" name="id_usuario" value=<?php echo $usuario->getId(); ?>  id="id_usuario">
		                		<button type="submit" class="btn btn-danger">Remover Amizade</button>
		            			</div>
		        				</form>
		        		<?php }
		        		if($flag=="naoeamigo"){ ?>
		        			<form method="POST" action="/admin/usuarios/solicitaramizade" role="form" class="clearfix">
					            <div class="col-md-6 form-group">
					            <input type="hidden" name="opcao" value="solicitar"  id="opcao">
					                <input type="hidden" name="id_usuario" value=<?php echo $usuario->getId(); ?>  id="id_usuario">
					                <button type="submit" class="btn btn-primary">Solicitar Amizade</button>
					            </div>
					        </form>

		        		<?php }
		        		if($flag=="jasolicitou"){
           					echo"<h5>Vc ja solicitou amizade com essa pessoa</h5>"; 
       						}
       					if($flag=="usuariojasolicitou"){ 
       						echo"<h5>usuario ja solicitou amizade com vc</h5>";
       					}	
		        		 ?>		 
						</div>
					</div>
				</div>
				<div class="col-md-6 column" id="mostrar">

				<?php if($flag=="usuariojasolicitou"){   ?>
						        <h5>Atenção!, essa pessoa ja solicitou sua amizade.</h5>
						        <h4>aceitar amizade?</h4>
						        <div class="col-md-6 form-group">
						        <form method="POST" action="/admin/usuarios/solicitaramizade" role="form" class="clearfix">
						            <input type="hidden" name="opcao" value="aceitar"  id="opcao">
						                <input type="hidden" name="id_usuario" value=<?php echo $usuario->getId(); ?>  id="id_usuario">
						                <button type="submit" class="btn btn-primary">Sim</button>
						        </form>
						        <form method="POST" action="/admin/usuarios/solicitaramizade" role="form" class="clearfix">
						              <input type="hidden" name="opcao" value="negar"  id="opcao">
						              <input type="hidden" name="id_usuario" value=<?php echo $usuario->getId(); ?>  id="id_usuario">
						              <button type="submit" class="btn btn-primary">Não</button>
						        </form>   
						  			</div>
						<?php }//fim if usuario ja solicitou ?>

					<div class="col-md-12 column" id="geral">
						<h3>Nome: <?php echo $usuario->getNome(); ?></h3>
              			<h3>Sobrenome: <?php echo $usuario->getSobrenome(); ?></h3>
              <br>
                
               <?php 
                if($usuario->getVisibilidadePerfil()=="publico" OR $usuario->getVisibilidadePerfil()=="somente amigos" && $flag=="eamigo" OR $flag=="evc"){
                ?>
                <h4>Email: <?php echo $usuario->getEmail(); ?></h4>
                <h4>Celular: <?php echo $usuario->getCelular(); ?></h4>
                <h4>Profissao: <?php echo $usuario->getProfissao(); ?></h4>
                <h4>Local de Trabalho: <?php echo $usuario->getLocaltrabalho(); ?></h4>
                <h4>Endereço: <?php echo $usuario->getEndereco(); ?></h4>
                <h4>Formação: <?php echo $usuario->getFormacao(); ?></h4>
                <h4>Data de Nacimento: <?php echo $usuario->getDataNasc(); ?></h4>

                <?php
                $jamostrou="sim";
                }
                ?>

                <?php 
                if($usuario->getVisibilidadePerfil()=="publico" && $jamostrou=="nao"){
                ?>
                <h4>Email: <?php echo $usuario->getEmail(); ?></h4>
                <h4>Celular: <?php echo $usuario->getCelular(); ?></h4>
                <h4>Profissao: <?php echo $usuario->getProfissao(); ?></h4>
                <h4>Local de Trabalho: <?php echo $usuario->getLocaltrabalho(); ?></h4>
                <h4>Endereço: <?php echo $usuario->getEndereco(); ?></h4>
                <h4>Formação: <?php echo $usuario->getFormacao(); ?></h4>
                <h4>Data de Nacimento: <?php echo $usuario->getDataNasc(); ?></h4>
                <a href="/admin/perfil/get-photo/id/<?php echo $usuario->getId(); ?>">Ver foto</a>
                <?php
                }
                ?>

                <?php 
                if($usuario->getVisibilidadePerfil()=="somente amigos" && $flag=="naoeamigo"){ ?>
                <div class="col-md-12"> 
                  <div class="well">
                    <h4>Somente os amigos do usuario podem ver seu perfil</h4>                 
                  </div>
                  </div>
                <?php
                } ?>

                <?php 
                if($usuario->getVisibilidadePerfil()=="somente eu" && $flag!="evc"){ ?>
                <div class="col-md-12"> 
                  <div class="well">
                    <h4>Somente o dono do Perfil pode ve-lo</h4>                 
                  </div>
                  </div>
                <?php
                } ?>
						<h3>
							Atualizações da pessoa
						</h3>
						<?php       

          foreach($usuario->getPosts() as $post) {
      $jamostrou="nao";
       foreach($meusdados as $userlogado) {
                foreach($userlogado->getAmigos() as $amigo) {
                    if($amigo->getId() == $post->getDono()->getId()){
        if($post->getVisibilidade()=="somente amigos" OR $post->getVisibilidade()=="publico" ){
      ?>
      <div class="row">    
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="/img/postdefault.jpg" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <h3><?php echo $post->getTitulo(); ?></h3>
              <div class="row">
                <div class="col-xs-9">
                  <p><?php echo $post->getPostComp(); ?></p>
                  <ul class="list-inline"><li><i>Ultima Edição:</i> <?php echo $post->getDataPost(); ?></li><li><a href="/admin/exibirpost/index/id/<?php echo $post->getId(); ?>"><i class="glyphicon glyphicon-comment"></i> <?php echo count($post->getComentarios()); ?> <i class="glyphicon glyphicon-thumbs-up"></i> <?php echo count($post->getCurtiram()); ?> <i class="glyphicon glyphicon-thumbs-down"></i> <?php echo count($post->getNaocurtiram()); ?> </a></li></ul>
                  <ul>Postado por: <a href="/admin/exibirperfil/index/id/<?php echo $post->getDono()->getId(); ?>"><?php echo $post->getDono()->getNome() ?></a></ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>

    <?php 
           $jamostrou="sim";
           }//fim do if visibilidade 
          }//fim do if verificar se é amigos
        }//fim fo if userlogado->getAmigos
      }//fim do if visibilidade


       if($post->getVisibilidade()=="publico" && $jamostrou=="nao" && $post->getDono()->getId()!=$this->session()->offsetGet('user')->getId() ){
      ?>
      <div class="row">    
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="/img/postdefault.jpg" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <h3><?php echo $post->getTitulo(); ?></h3>
              <div class="row">
                <div class="col-xs-9">
                  <p><?php echo $post->getPostComp(); ?></p>
                  <ul class="list-inline"><li><i>Ultima Edição:</i> <?php echo $post->getDataPost(); ?></li><li><a href="/admin/exibirpost/index/id/<?php echo $post->getId(); ?>"><i class="glyphicon glyphicon-comment"></i> <?php echo count($post->getComentarios()); ?> <i class="glyphicon glyphicon-thumbs-up"></i> <?php echo count($post->getCurtiram()); ?> <i class="glyphicon glyphicon-thumbs-down"></i> <?php echo count($post->getNaocurtiram()); ?> </a></li></ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>

    <?php 
           }//fim do if visibilidade publico
    }//fim do foreach posts 
    
    if($post->getDono()->getId()==$this->session()->offsetGet('user')->getId()){
    ?>
      <div class="row">    
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="/img/postdefault.jpg" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <h3><?php echo $post->getTitulo(); ?></h3>
              <div class="row">
                <div class="col-xs-9">
                  <p><?php echo $post->getPostComp(); ?></p>
                  <ul class="list-inline"><li><i>Ultima Edição:</i> <?php echo $post->getDataPost(); ?></li><li><a href="/admin/exibirpost/index/id/<?php echo $post->getId(); ?>"><i class="glyphicon glyphicon-comment"></i> <?php echo count($post->getComentarios()); ?> <i class="glyphicon glyphicon-thumbs-up"></i> <?php echo count($post->getCurtiram()); ?> <i class="glyphicon glyphicon-thumbs-down"></i> <?php echo count($post->getNaocurtiram()); ?> </a></li></ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>
    <?php
  $flag="postDoUserLogado";
}// fim do if verifica se é meu post
?>       

					</div>
				</div>
				<div class="col-md-4 column" align='auto' id="amigos">
				
				<?php 
					if(count($usuario->getAmigos())>0){
					    ?>
					    <h3>Amigos(<?php echo count($usuario->getAmigos()); ?>):</h3>
					    <?php
					 foreach($usuario->getAmigos() as $amigo) { ?>
					     <h5> <a class="story-img" href="/admin/exibirperfil/index/id/<?php echo $amigo->getId(); ?>"><img src="/admin/perfil/get-photo/id/<?php echo $amigo->getId(); ?>" style="width:30px;height:30px" class="img-circle"><?php echo $amigo->getNome()?></a></h5>
					<?php 
					 }//fim do foreach
					}//fim do if
					?>

					<?php }//fim foreach usuarios
     				?>
		
				</div>
			</div>
		</div>
	</div>
</div>			


		<nav class="navbar navbar-default navbar-inverse navbar-static-bottom" role="navigation">
			<!--<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
			</div>-->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li>
						<h5></h5>
					</li>
				</ul>
			</div>
		</nav>
		
