<div class="container">
  <div class="row">
    
    <div class="col-md-12"> 
      
      <div class="panel">
        <div class="panel-body">     

     <?php foreach($eventos as $evento) { ?>
      <div class="row">    
            <br>
            <div class="col-md-2 col-sm-3 text-center">
              <a class="story-img" href="#"><img src="/img/postdefault.jpg" style="width:100px;height:100px" class="img-circle"></a>
            </div>
            <div class="col-md-10 col-sm-9">
              <h3><?php echo $evento->getTitulo(); ?></h3>
              <div class="row">
                <div class="col-xs-9">
                  <p><?php  echo $evento->getEventoComp(); ?></p>
                  <ul class="list-inline"><li><i>Ultima Edição:</i> <?php echo $evento->getDataEvento(); ?></li><li><a href="/admin/exibirevento/index/id/<?php echo $evento->getId(); ?>"><i class="glyphicon glyphicon-comment"></i> <?php echo count($evento->getComentarios()); ?> Comentários
                    <li><span class="glyphicon glyphicon-user"></span>Participantes: <?php echo count($evento->getParticipantes()); ?></a></li>
                  </ul>
                  </div>
                <div class="col-xs-3"></div>
              </div>
              <br><br>
            </div>
          </div>
          <hr>

    <?php } ?>       
          
        </div>
      </div>
                                      
    </div><!--/col-12-->
  </div>
</div>
</hr>

<!-- Posted Comments -->
<!-- Comment -->
<?php foreach($evento->getComentarios() as $comentario) { ?>
<div class="media">
    <a class="pull-left" href="/admin/exibirperfil/index/id/<?php echo $comentario->getUsuario()->getId(); ?>">
        <img class="media-object" style="width:64px;height:64px" src="/img/profile.jpg" alt="">
    </a>
    <div class="media-body">
        <h4 class="media-heading"><?php echo $comentario->getUsuario()->getNome(); ?>
            <small><?php echo $comentario->getDataComentario(); ?></small>
        </h4>
        <?php  echo $comentario->getComentario(); ?>
    </div>
</div>
<?php } ?>

<br>

<div class="col-md-12"> 
        <div class="col-md-4">
    <div class="well">
     
       
     
     <?php       

        $flag="naoconfirmou";

        foreach($evento->getParticipantes() as $participante) {
                    if($participante->getId() == $this->session()->offsetGet('user')->getId()){
                      //echo $eventoComparar->getId();
                      $flag="confirmou";
                    }
                }

          if($flag=="naoconfirmou"){     
              ?>

        <h4>Confirmar Presença?</h4>
        <form method="POST" action="/admin/eventos/confirmarpresenca" role="form" class="clearfix">
            <div class="col-md-6 form-group">
            <input type="hidden" name="opcao" value="confirmar"  id="opcao">
                <input type="hidden" name="id_evento" value=<?php echo $evento->getId(); ?>  id="id_evento">
                <button type="submit" class="btn btn-primary">Sim</button>
            </div>
        </form>  

        <?php     

          }

          if($flag=="confirmou"){
          ?>
            <h5>Atenção!, vc ja confirmou presença nesse evento.</h5>
           <h4>Remover Presença?</h4>
        <form method="POST" action="/admin/eventos/confirmarpresenca" role="form" class="clearfix">
            <div class="col-md-6 form-group">
            <input type="hidden" name="opcao" value="remover"  id="opcao">
                <input type="hidden" name="id_evento" value=<?php echo $evento->getId(); ?>  id="id_evento">
                <button type="submit" class="btn btn-primary">Sim</button>
            </div>
        </form> 

          <?php
        }
            ?>
    </div>
</div>
</div>

<br><br>
<!-- Blog Comments -->
<!-- Comments Form -->
    <div class="col-md-12"> 
        <div class="col-md-12">
    <div class="well">
     
        <h4>Deixe seu comentário</h4>
     
        <form method="POST" action="/admin/comentarios/novocomentevento/" role="form" class="clearfix">
     
            <div class="col-md-12 form-group">
                <label class="sr-only" for="email">Comentário</label>
                <textarea class="form-control" name="comentario" id="comentario" placeholder="Comentário"></textarea>
            </div>
     
            <div class="col-md-12 form-group text-right">
                <input type="hidden" name="id_evento" value=<?php echo $evento->getId(); ?>  id="id_evento">
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
     
        </form>                   
    </div>
</div>
</div>
<?php

echo $this->paginationControl(
    // o objeto de paginacao
    $eventos,
    //tipos de paginacao (elastic, all, sliding, Juping) mais em zend/paginator exemple-pagination-controls
    'sliding',
    // a parcial usada para gerar o html para a paginacao
    'admin/partials/paginator/paginator.phtml',
    //a rota utulizada na paginacao
    array(
        'route' => 'eventos'
    )
);
?>
